import type { ConfigId, PipelineConfig } from "@/src/agent/types";

const BASE = {
  model: "claude-opus-5",
  verifierModel: "claude-opus-5",
  effort: "high",
  verifierEffort: "xhigh",
  maxRepairRounds: 2,
  workerMaxIterations: 12,
  plannerMaxIterations: 8,
  sectionPageSize: 40,
  concurrency: 6,
  elementAware: false,
  preciseElementProtocol: false,
  longDocumentPlanning: false,
  longDocumentThresholdWords: 15_000,
  elementMarkedMemory: false,
} as const;

export const CONFIGS: Record<ConfigId, PipelineConfig> = {
  "b0-chat": {
    ...BASE, id: "b0-chat", label: "Chat baseline", description: "One free-text review call without the playbook, plus one cheap extraction call; deterministic memo.",
    singlePrompt: true, playbookInContext: false, docModel: false, planner: false, perRuleWorkers: false,
    toolValidation: false, verifier: false, precedentMemory: false, monolith: false,
  },
  "b1-prompt": {
    ...BASE, id: "b1-prompt", label: "Prompt baseline", description: "Exactly one structured findings call with the full playbook; deterministic memo.",
    singlePrompt: true, playbookInContext: true, docModel: false, planner: false, perRuleWorkers: false,
    toolValidation: false, verifier: false, precedentMemory: false, monolith: false,
  },
  "i1-docmodel": {
    ...BASE, id: "i1-docmodel", label: "Document model", description: "Planner plus paragraph-addressed document access.",
    singlePrompt: false, playbookInContext: true, docModel: true, planner: true, perRuleWorkers: false,
    toolValidation: false, verifier: false, precedentMemory: false, monolith: false,
  },
  "i2-workers": {
    ...BASE, id: "i2-workers", label: "Validated workers", description: "One tool-using worker per rule with boundary validation.",
    singlePrompt: false, playbookInContext: true, docModel: true, planner: true, perRuleWorkers: true,
    toolValidation: true, verifier: false, precedentMemory: false, monolith: false,
  },
  "i3-verifier": {
    ...BASE, id: "i3-verifier", label: "Verified workers", description: "Independent verification and bounded repair.",
    singlePrompt: false, playbookInContext: true, docModel: true, planner: true, perRuleWorkers: true,
    toolValidation: true, verifier: true, precedentMemory: false, monolith: false,
  },
  "i4-memory": {
    ...BASE, id: "i4-memory", label: "Precedent memory", description: "Verified workers with approved-clause retrieval.",
    singlePrompt: false, playbookInContext: true, docModel: true, planner: true, perRuleWorkers: true,
    toolValidation: true, verifier: true, precedentMemory: true, monolith: false,
  },
  "i5-elements": {
    ...BASE,
    id: "i5-elements",
    label: "Element-complete redlines",
    description: "Atomic position checklists, element-mapped drafting, deterministic minimality, and fresh-context element verification with up to three repairs.",
    singlePrompt: false,
    playbookInContext: true,
    docModel: true,
    planner: true,
    perRuleWorkers: true,
    toolValidation: true,
    verifier: true,
    precedentMemory: false,
    elementAware: true,
    monolith: false,
    effort: "high",
    verifierEffort: "high",
    maxRepairRounds: 3,
    workerMaxIterations: 18,
  },
  "i6-longdoc": {
    ...BASE,
    id: "i6-longdoc",
    label: "Long-document elements",
    description: "i5 element-complete drafting plus, at 15,000 words, whole-document per-rule search planning, definition-first context, paginated worker reads, and bounded raised planner/worker budgets.",
    singlePrompt: false,
    playbookInContext: true,
    docModel: true,
    planner: true,
    perRuleWorkers: true,
    toolValidation: true,
    verifier: true,
    precedentMemory: false,
    elementAware: true,
    longDocumentPlanning: true,
    monolith: false,
    effort: "high",
    verifierEffort: "high",
    maxRepairRounds: 3,
    workerMaxIterations: 24,
    plannerMaxIterations: 28,
  },
  "i7-precise": {
    ...BASE,
    id: "i7-precise",
    label: "Official-judge precision",
    description: "Round-1 detection locked before prose-derived element repair, official minimality gates, and a medium-effort judge-shaped verifier.",
    singlePrompt: false,
    playbookInContext: true,
    docModel: true,
    planner: true,
    perRuleWorkers: true,
    toolValidation: true,
    verifier: true,
    precedentMemory: false,
    elementAware: true,
    preciseElementProtocol: true,
    monolith: false,
    effort: "high",
    verifierEffort: "medium",
    maxRepairRounds: 1,
    workerMaxIterations: 14,
  },
  "x-monolith": {
    ...BASE, id: "x-monolith", label: "Monolith", description: "Exactly one validated tool loop handles and self-checks every rule; no independent verifier or memo call.",
    singlePrompt: false, playbookInContext: true, docModel: true, planner: false, perRuleWorkers: false,
    toolValidation: true, verifier: false, precedentMemory: false, monolith: true,
  },
  final: {
    ...BASE, id: "final", label: "Final", description: "Planner, validated workers, verifier repair, and precedent memory.",
    singlePrompt: false, playbookInContext: true, docModel: true, planner: true, perRuleWorkers: true,
    toolValidation: true, verifier: true, precedentMemory: true, monolith: false,
  },
  "final-v2": {
    ...BASE,
    id: "final-v2",
    label: "Final v2",
    description: "i6's thresholded long-document element completeness plus approved precedent language returned as element-labelled drafting templates.",
    singlePrompt: false,
    playbookInContext: true,
    docModel: true,
    planner: true,
    perRuleWorkers: true,
    toolValidation: true,
    verifier: true,
    precedentMemory: true,
    elementAware: true,
    longDocumentPlanning: true,
    elementMarkedMemory: true,
    monolith: false,
    effort: "high",
    verifierEffort: "high",
    maxRepairRounds: 3,
    workerMaxIterations: 24,
    plannerMaxIterations: 28,
  },
  "final-v3": {
    ...BASE,
    id: "final-v3",
    label: "Final v3",
    description: "i7 precision with final-v2 precedent memory and i6 thresholded long-document planning.",
    singlePrompt: false,
    playbookInContext: true,
    docModel: true,
    planner: true,
    perRuleWorkers: true,
    toolValidation: true,
    verifier: true,
    precedentMemory: true,
    elementAware: true,
    preciseElementProtocol: true,
    longDocumentPlanning: true,
    elementMarkedMemory: true,
    monolith: false,
    effort: "high",
    verifierEffort: "medium",
    maxRepairRounds: 1,
    workerMaxIterations: 24,
    plannerMaxIterations: 28,
  },
  "final-v4": {
    ...BASE,
    id: "final-v4",
    label: "Final v4 (length router)",
    description:
      "The shipped configuration: a length router over the two best-measured pipelines — i7-precise below 15,000 words, i6-longdoc at or above it. Precedent memory is off (it measured as a non-result). Runs execute the routed configuration's prompts unchanged and share its replay caches.",
    singlePrompt: false,
    playbookInContext: true,
    docModel: true,
    planner: true,
    perRuleWorkers: true,
    toolValidation: true,
    verifier: true,
    precedentMemory: false,
    elementAware: true,
    monolith: false,
    effort: "high",
    verifierEffort: "high",
    maxRepairRounds: 3,
    routes: { thresholdWords: 15_000, below: "i7-precise", atOrAbove: "i6-longdoc" },
  },
};

export function getConfig(id: string): PipelineConfig {
  const config = CONFIGS[id as ConfigId];
  if (!config) throw new Error(`Unknown pipeline config: ${id}`);
  return config;
}

/**
 * The configuration that actually runs for a document: a router config resolves to its routed member by word count;
 * every other config resolves to itself. Callers key caches and prompts on the resolved id.
 */
export function resolveConfig(config: PipelineConfig, document: { stats: { words: number } }): PipelineConfig {
  if (!config.routes) return config;
  const target = document.stats.words >= config.routes.thresholdWords ? config.routes.atOrAbove : config.routes.below;
  return resolveConfig(getConfig(target), document);
}
